name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@de3f8a372eeb4ff134520743f33222075c67be89 # v.0.01
    with:
      python-version: "3.14"
      tox-env: lint

  check:
    name: Check
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@de3f8a372eeb4ff134520743f33222075c67be89 # v.0.01
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: check

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

  test:
    name: Unit tests
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@de3f8a372eeb4ff134520743f33222075c67be89 # v.0.01
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: coverage

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
